rules:
  default:
    protection:
      required_status_checks:
        context:
          - continuous-integration/travis/pr
      required_pull_request_reviews:
        required_approving_review_count: 1
